print('apps are ready for our fir deployment')
print('please, let start deployment1')
print('please, we are starting deployment2')
print('please, testing rebase from merge')
print('please, adding second line for testing rebase from merge')
